In [186]:
import numpy as np
import math
import copy

## Question 2

In [2]:
gamma_pi=np.zeros((25,25))  # coeffiecient matrix
r_pi=np.zeros(25) #constant matrix
r=5 #number of rows
c=5 #number of columns
gamma=0.9
A_initial=[0,1]
A_final=[4,1]
B_initial=[0,3]
B_final=[2,3]
A_reward=10
B_reward=5
pi=0.25 #probability of each action
x_steps=[1,-1,0,0]
y_steps=[0,0,1,-1]

In [3]:
def next_cell(x,y): #returns a list of all valid cells we can transition to from (i,j)
    cells=[]
    for i in range(len(x_steps)):
        if (x-x_steps[i]>=0 and x-x_steps[i]<r) and (y-y_steps[i]>=0 and y-y_steps[i]<c):
            cells.append([x-x_steps[i],y-y_steps[i]])
    return cells

In [4]:
for i in range(r): # for all s in S
    for j in range(c):# for all s in S
        pos=[] 
        pos.append(i)
        pos.append(j)
        next_states=np.zeros((r,c)) # for given s,  matrix of all possible s'
        if pos==A_initial: # if s=A
            next_states[A_final[0]][A_final[1]]=-(4*pi*gamma) # all four choices lead to A'
            next_states[i][j]=1 # no transition from s to s
            r_pi[i*r+j]=A_reward # total reward is calculated for all state s = pi*r for each action,r 
        elif pos==B_initial: # if s=B
            next_states[B_final[0]][B_final[1]]=-(4*pi*gamma)
            next_states[i][j]=1
            r_pi[i*r+j]=B_reward
        else: # if s belongs to states other than A and B
            cells=next_cell(i,j) # all valid moves
            if len(cells)==2: # corner case
                for k in cells:
                    next_states[k[0]][k[1]]=-(pi*gamma)  
                next_states[i][j]=(1-2*pi*gamma) # for transition from s to s and reward=-1
                r_pi[i*r+j]=2*-1*pi
            elif len(cells)==3: # edge case
                for k in cells:
                    next_states[k[0]][k[1]]=-(pi*gamma)
                next_states[i][j]=(1-pi*gamma)
                r_pi[i*r+j]=1*-1*pi
            elif len(cells)==4: #center case
                for k in cells:
                    next_states[k[0]][k[1]]=-(pi*gamma)
                next_states[i][j]=1
                r_pi[i*r+j]=0
        gamma_pi[i*r+j]=next_states.ravel()  # updating values in coefficient matrix          

In [5]:
gamma_pi

array([[ 0.55 , -0.225,  0.   ,  0.   ,  0.   , -0.225,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.9  ,  0.   ,  0.   ,
         0.   ],
       [ 0.   , -0.225,  0.775, -0.225,  0.   ,  0.   ,  0.   , -0.225,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.9  ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   , -0.225,  0.55 ,  0.   ,  0.   ,  0. 

In [6]:
r_pi

array([-0.5 , 10.  , -0.25,  5.  , -0.5 , -0.25,  0.  ,  0.  ,  0.  ,
       -0.25, -0.25,  0.  ,  0.  ,  0.  , -0.25, -0.25,  0.  ,  0.  ,
        0.  , -0.25, -0.5 , -0.25, -0.25, -0.25, -0.5 ])

In [7]:
v_pi= np.linalg.inv(gamma_pi) @ r_pi # calculating x in Ax=B by x=A^-1*B

In [8]:
v_pi 

array([ 3.30899634,  8.78929186,  4.42761918,  5.32236759,  1.49217876,
        1.52158807,  2.99231786,  2.25013995,  1.9075717 ,  0.54740271,
        0.05082249,  0.73817059,  0.67311326,  0.35818621, -0.40314114,
       -0.9735923 , -0.43549543, -0.35488227, -0.58560509, -1.18307508,
       -1.85770055, -1.34523126, -1.22926726, -1.42291815, -1.97517905])

In [9]:
np.round(np.reshape(v_pi,(5,5)),1) # rounding values to 1 decimal place

array([[ 3.3,  8.8,  4.4,  5.3,  1.5],
       [ 1.5,  3. ,  2.3,  1.9,  0.5],
       [ 0.1,  0.7,  0.7,  0.4, -0.4],
       [-1. , -0.4, -0.4, -0.6, -1.2],
       [-1.9, -1.3, -1.2, -1.4, -2. ]])

## Question 4

In [10]:
V_0=np.round(np.reshape(v_pi,(5,5)),1) # initialising V_0=V_pi so that it can be used in value iteration

In [11]:
theta=0.000001 #setting theta value to capture convergence of V_pi

In [12]:
while 1:
    delta=0
    for i in range(r):
        for j in range(c):
            v=V_0[i][j]
            pos=[]
            pos.append(i)
            pos.append(j)
            if pos==A_initial: # if s=A
                V_0[i][j]=A_reward+gamma*V_0[A_final[0]][A_final[1]] #updating V_pi
                delta=max(delta,abs(v-V_0[i][j])) #checking difference between old and new state values
            elif pos==B_initial: #if s=B
                V_0[i][j]=B_reward+gamma*V_0[B_final[0]][B_final[1]]
                delta=max(delta,abs(v-V_0[i][j]))
            else: # other cases where s is not equal to A or B
                cells=next_cell(i,j)
                if len(cells)==2:
                    value=[]
                    for k in cells:
                        value.append(0+gamma*V_0[k[0]][k[1]])
                    value.append(-1+gamma*V_0[i][j])
                    V_0[i][j]=max(value)
                    delta=max(delta,abs(v-V_0[i][j]))
                elif len(cells)==3:
                    value=[]
                    for k in cells:
                        value.append(0+gamma*V_0[k[0]][k[1]])
                    value.append(-1+gamma*V_0[i][j])
                    V_0[i][j]=max(value)
                    delta=max(delta,abs(v-V_0[i][j]))
                elif len(cells)==4:
                    value=[]
                    for k in cells:
                        value.append(0+gamma*V_0[k[0]][k[1]])
                    V_0[i][j]=max(value)
                    delta=max(delta,abs(v-V_0[i][j]))
    if delta<theta: # if the difference between the old and new state value less than theta then we stop the iteration
        break

In [17]:
V_0=np.round(V_0,1)

In [18]:
V_0

array([[22. , 24.4, 22. , 19.4, 17.5],
       [19.8, 22. , 19.8, 17.8, 16. ],
       [17.8, 19.8, 17.8, 16. , 14.4],
       [16. , 17.8, 16. , 14.4, 13. ],
       [14.4, 16. , 14.4, 13. , 11.7]])

In [39]:
pi_star=[]
steps=[]
directions=[]
steps.append([-1,0])
directions.append("up")
steps.append([1,0])
directions.append("down")
steps.append([0,1])
directions.append("right")
steps.append([0,-1])
directions.append("left")

In [42]:
for i in range(r):
    for j in range(c):
        pos=[]
        pos.append(i)
        pos.append(j)
        if pos==A_initial: # for s=A, all actions lead to same s'
            pi_star.append(["left","right","up","down"])
        elif pos==B_initial: # similar to above case
            pi_star.append(["left","right","up","down"])
        else: 
            cells=next_cell(i,j)
            possible=[]
            if len(cells)==2: # corner case
                value=[]
                for k in cells:
                    value.append(0+gamma*V_0[k[0]][k[1]])
                value.append(-1+gamma*V_0[i][j])
                dirn=np.argwhere(value == np.amax(value)).flatten().tolist() # computing argmax to get the optimal action
                for l in dirn: # to check for multiple optimal actions
                    if l<len(cells):
                        v=steps.index(list(np.array(cells[l])-np.array([i,j])))
                        possible.append(directions[v])
                    else:
                        for p in steps:
                            rel=list(np.array(p)+np.array([i,j]))
                            if rel not in cells:
                                possible.append(directions[steps.index(p)])
                pi_star.append(possible)
            elif len(cells)==3: # edge case
                value=[]
                for k in cells:
                    value.append(0+gamma*V_0[k[0]][k[1]])
                value.append(-1+gamma*V_0[i][j])
                dirn=np.argwhere(value == np.amax(value)).flatten().tolist()
                for l in dirn:
                    if l<len(cells):
                        v=steps.index(list(np.array(cells[l])-np.array([i,j])))
                        possible.append(directions[v])
                    else:
                        for p in steps:
                            rel=list(np.array(p)+np.array([i,j]))
                            if rel not in cells:
                                possible.append(directions[steps.index(p)])
                pi_star.append(possible)
            elif len(cells)==4: # center case
                value=[]
                for k in cells:
                    value.append(0+gamma*V_0[k[0]][k[1]])
                value.append(-1+gamma*V_0[i][j])
                dirn=np.argwhere(value == np.amax(value)).flatten().tolist()
                for l in dirn:
                    if l<len(cells):
                        v=steps.index(list(np.array(cells[l])-np.array([i,j])))
                        possible.append(directions[v])
                    else:
                        for p in steps:
                            rel=list(np.array(p)+np.array([i,j]))
                            if rel not in cells:
                                possible.append(directions[steps.index(p)])
                pi_star.append(possible) # appending list of optimal paths in case of multiple optimal paths

In [43]:
pi_star

[['right'],
 ['left', 'right', 'up', 'down'],
 ['left'],
 ['left', 'right', 'up', 'down'],
 ['left'],
 ['up', 'right'],
 ['up'],
 ['up', 'left'],
 ['left'],
 ['left'],
 ['up', 'right'],
 ['up'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'right'],
 ['up'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'right'],
 ['up'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'left'],
 ['right'],
 ['left', 'right', 'up', 'down'],
 ['left'],
 ['left', 'right', 'up', 'down'],
 ['left'],
 ['up', 'right'],
 ['up'],
 ['up', 'left'],
 ['left'],
 ['left'],
 ['up', 'right'],
 ['up'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'right'],
 ['up'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'right'],
 ['up'],
 ['up', 'left'],
 ['up', 'left'],
 ['up', 'left']]

## Question 6

## Policy Iteration

In [187]:
r=4
c=4
gamma=1 # undiscounted case
terminal=[[0,0],[3,3]] # terminal cases
theta=0.000001
V_pi=np.zeros((r,c)) # state values for each state
pi_k=np.zeros((r,c,4)) # policy function for each state for each action
initial_pi=[0.25,0.25,0.25,0.25] #[left,right,up,down]
dirn=["left","right","up","down"]

In [188]:
#initialization
for i in range(r):
    for j in range(c):
        pi_k[i][j]=initial_pi #intitializing with 0

In [189]:
def pol_eval():
    print("Evaluating")
    while True:
        delta=0
        for i in range(r):
            for j in range(c):
                v=copy.deepcopy(V_pi[i][j]) # storing old state value
                pos=[]
                pos.append(i)
                pos.append(j)
                if pos not in terminal: # for non terminal states
                    V_pi[i][j]=0
                    if (i>=0 and i<r) and (j-1>=0 and j-1<c): # left valid move
                        V_pi[i][j]+=pi_k[i][j][0]*(-1+gamma*V_pi[i][j-1])
                    else: # else left move is out of bounds
                        V_pi[i][j]+=pi_k[i][j][0]*(-1+gamma*v)
                    if (i>=0 and i<r) and (j+1>=0 and j+1<c): # same for right
                        V_pi[i][j]+=pi_k[i][j][1]*(-1+gamma*V_pi[i][j+1])
                    else:
                        V_pi[i][j]+=pi_k[i][j][1]*(-1+gamma*v)
                    if (i-1>=0 and i-1<r) and (j>=0 and j<c): # same for up
                        V_pi[i][j]+=pi_k[i][j][2]*(-1+gamma*V_pi[i-1][j])
                    else:
                        V_pi[i][j]+=pi_k[i][j][2]*(-1+gamma*v)
                    if (i+1>=0 and i+1<r) and (j>=0 and j<c): # same for down
                        V_pi[i][j]+=pi_k[i][j][3]*(-1+gamma*V_pi[i+1][j])
                    else:
                        V_pi[i][j]+=pi_k[i][j][3]*(-1+gamma*v)
                    delta=max(delta,abs(v-V_pi[i][j])) # computing difference between old and new state values
#                     print(delta)
        if delta<theta: # if difference less than  theta bound, then we stop evaluation as we have converged to V_pi
            break

In [190]:
while True:
    print("ITERATION\n")
    pol_eval() # policy evaluation
    print(V_pi) 
    print("Improving\n")
    state=True # state true to capture condition of optimal policy
    for i in range(r): # for each state s in S
        for j in range(c):
            old=copy.deepcopy(pi_k[i][j]) # saving old policy function
#             print("old= ",old)
            pos=[]
            pos.append(i)
            pos.append(j)
            if pos not in terminal:
                value=[0]*len(dirn)
                if (i>=0 and i<r) and (j-1>=0 and j-1<c): # calculating r + gamma*Vs' for left
                    value[0]=(-1+gamma*V_pi[i][j-1])
                else:
                    value[0]=(-1+gamma*V_pi[i][j])
                if (i>=0 and i<r) and (j+1>=0 and j+1<c): # same for right move
                    value[1]=(-1+gamma*V_pi[i][j+1])
                else:
                    value[1]=(-1+gamma*V_pi[i][j])
                if (i-1>=0 and i-1<r) and (j>=0 and j<c): # same for up move
                    value[2]=(-1+gamma*V_pi[i-1][j])
                else:
                    value[2]=(-1+gamma*V_pi[i][j])
                if (i+1>=0 and i+1<r) and (j>=0 and j<c): # same for down move
                    value[3]=(-1+gamma*V_pi[i+1][j])
                else:
                    value[3]=(-1+gamma*V_pi[i][j])
#                 print("value= ",value)
                best=np.argwhere(value == np.amax(value)).flatten().tolist() # getting the optimal moves from all possible moves
#                 print("best= ",best)
                new=[0]*len(dirn)
                for b in range(len(new)): # iterating over all optimal moves. This takes care of the bug mentioned in the exercise 4.4 as now we change probabilites to go to all optimal states rather than only the first occurence
                    if b in best:
                        new[b]=1/len(best) # 1/total optimal actions
                pi_k[i][j]=new # assigning new policy function
#                 print("new= ",pi_k[i][j])
                st=0
                for g in range(len(old)): # if old and new policy function same then that means we have converged to the optimal policy( should be for all states)
                    if old[g]!=pi_k[i][j][g]:
                        state=False
                        break
                print(pi_k[i][j])
#                 print(old," ",new)
#                 print("hello")
    if state: # if converged then returning 
        final_directions=[]
        print("FINAL\n")
        print("V*\n")
        print(V_pi)
        print("pi*\n")
        print(pi_k)
        for i in range(r):
            for j in range(c):
                pos=[]
                pos.append(i)
                pos.append(j)
                if pos in terminal: # if at terminal state
                    final_directions.append("Terminal")
                else: # if at any other state
                    act=np.argwhere(pi_k[i][j] == np.amax(pi_k[i][j])).flatten().tolist() # getting the optimal actions
                    s=""
                    for y in act:
                        s+=dirn[y]+" "
                    final_directions.append(s)
        print("Optimal Actions\n")
        print(final_directions) # all optimal actions for each state
        break

ITERATION

Evaluating
[[  0.         -13.99999335 -19.99999044 -21.99998948]
 [-13.99999335 -17.99999184 -19.99999114 -19.99999125]
 [-19.99999044 -19.99999114 -17.99999253 -13.99999442]
 [-21.99998948 -19.99999125 -13.99999442   0.        ]]
Improving

[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[0. 0. 1. 0.]
[0.5 0.  0.5 0. ]
[1. 0. 0. 0.]
[0. 0. 0. 1.]
[0. 0. 1. 0.]
[0. 0. 1. 0.]
[0.  0.5 0.  0.5]
[0. 0. 0. 1.]
[0. 0. 1. 0.]
[0. 1. 0. 0.]
[0. 1. 0. 0.]
ITERATION

Evaluating
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
Improving

[1. 0. 0. 0.]
[1. 0. 0. 0.]
[0.5 0.  0.  0.5]
[0. 0. 1. 0.]
[0.5 0.  0.5 0. ]
[0.25 0.25 0.25 0.25]
[0. 0. 0. 1.]
[0. 0. 1. 0.]
[0.25 0.25 0.25 0.25]
[0.  0.5 0.  0.5]
[0. 0. 0. 1.]
[0.  0.5 0.5 0. ]
[0. 1. 0. 0.]
[0. 1. 0. 0.]
ITERATION

Evaluating
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
Improving

[1. 0. 0. 0.]
[1. 0. 0. 0.]
[0.5 0.  0.  0.5]
[0. 0. 1. 0.]
[0.5 0.  0.5 0. ]
[0.25 0.25 0.25 

## Value Iteration

In [191]:
V_pi=np.zeros((r,c))
while True:
    delta=0
    for i in range(r):
        for j in range(c):
            v=copy.deepcopy(V_pi[i][j]) # storing old state value
            pos=[]
            pos.append(i)
            pos.append(j)
            if pos not in terminal:
                value=[0]*len(dirn)
                if (i>=0 and i<r) and (j-1>=0 and j-1<c): # calculating r + gamma*Vs' for left
                    value[0]=(-1+gamma*V_pi[i][j-1])
                else:
                    value[0]=(-1+gamma*V_pi[i][j])
                if (i>=0 and i<r) and (j+1>=0 and j+1<c): # same for right move
                    value[1]=(-1+gamma*V_pi[i][j+1])
                else:
                    value[1]=(-1+gamma*V_pi[i][j])
                if (i-1>=0 and i-1<r) and (j>=0 and j<c): # same for up move
                    value[2]=(-1+gamma*V_pi[i-1][j])
                else:
                    value[2]=(-1+gamma*V_pi[i][j])
                if (i+1>=0 and i+1<r) and (j>=0 and j<c): # same for down move
                    value[3]=(-1+gamma*V_pi[i+1][j])
                else:
                    value[3]=(-1+gamma*V_pi[i][j])
                V_pi[i][j]=max(value)
                delta=max(delta,abs(v-V_pi[i][j]))
    print("V_pi\n")
    print(V_pi)
    if delta<theta:
        break                

V_pi

[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
V_pi

[[ 0. -1. -2. -2.]
 [-1. -2. -2. -2.]
 [-2. -2. -2. -1.]
 [-2. -2. -1.  0.]]
V_pi

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
V_pi

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


In [192]:
final_directions=[]
for i in range(r):
    for j in range(c):
        pos=[]
        pos.append(i)
        pos.append(j)
        if pos in terminal: # if at terminal state
            final_directions.append("Terminal")
        else: # if at any other state
            act=np.argwhere(pi_k[i][j] == np.amax(pi_k[i][j])).flatten().tolist() # getting the optimal actions
            s=""
            for y in act:
                s+=dirn[y]+" "
            final_directions.append(s)
print("Optimal Actions\n")
print(final_directions) # all optimal actions for each state

Optimal Actions

['Terminal', 'left ', 'left ', 'left down ', 'up ', 'left up ', 'left right up down ', 'down ', 'up ', 'left right up down ', 'right down ', 'down ', 'right up ', 'right ', 'right ', 'Terminal']
